name: 'determine-account-action'
description: "determine stage"
runs:
  using: composite
  steps:
    - name: Determine Account
      id: account
      run: |
        if [ "${FEATURE_STAGE}" == "prod" ]; then
          echo "AWS_ACCOUNT=${PROD}" >> $GITHUB_ENV
        else
          echo "AWS_ACCOUNT=${DEV}" >> $GITHUB_ENV
        fi
      shell: bash