#!/bin/bash

if [ "${FEATURE_STAGE}" == "prod" ]; then
  echo "AWS_ACCOUNT=${{ secrets.STS_PROD_AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
else
  echo "AWS_ACCOUNT=${{ secrets.STS_DEV_AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
fi