name: 'set-publish-token'
description: "Move away from read-only token to use publish token"
inputs:
  packageManager:
    description: "Package manager to use.  yarn3 vs yarn"
    required: false
    default: "yarn3"
  npmjsPublishToken:
    description: "NPMJS token with publishing permissions"
    required: true
runs:
  using: composite
  steps:
    - name: set publish token
      id: set-publish-token
      run: ${{ github.action_path }}/set-publish-token
      env:
        packageManager: ${{ inputs.packageManager }}
        token: ${{ inputs.npmjsPublishToken }}
      shell: bash