name: Author Assigner
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-latest'"
        required: false
        type: string
        default: "ubuntu-latest"
jobs:
  assignAuthor:
    name: Assign author
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 5
    steps:
      - name: assign
        uses: technote-space/assign-author@v1
