name: PR AutoLabeler
on:
  workflow_call
jobs:
  label:
    name: Auto Labeler
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: pr autolabeler
        uses: actions/labeler@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
