name: PR AutoLabeler
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-22.04'"
        required: false
        type: string
        default: "ubuntu-22.04"
jobs:
  label:
    name: Auto Labeler
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 3
    steps:
      - name: pr autolabeler
        uses: actions/labeler@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
