name: Dependabot AutoMerger
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-22.04'"
        required: false
        type: string
        default: "ubuntu-22.04"
      mergeTries:
        description: "how many times to attempt merging"
        required: false
        type: string
        default: "10"
      mergeRetrySleep:
        description: "how long to wait between merge tries, in milliseconds"
        required: false
        type: string
        default: "60000"
jobs:
  dependabot-auto-merge:
    name: Dependabot AutoMerger
    if: github.actor == 'dependabot[bot]'
    timeout-minutes: 20
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Wait
        uses: kibertoad/wait-action@1.0.1
        with:
          time: 30
      - name: Auto Merge
        id: auto-merge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_LABELS: "dependencies,!config,!actions,!bug,!cloudformation,!documentation,!duplicate,!enhancement,!good first issue,!help wanted,!invalid,!prod,!question,!wontfix,!wip,!work in progress"
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
          MERGE_FORKS: "false"
          MERGE_RETRIES: ${{ inputs.mergeTries }}
          MERGE_RETRY_SLEEP: ${{ inputs.mergeRetrySleep }}
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
      - name: feedback
        if: steps.auto-merge.outputs.mergeResult == 'merged'
        run: echo "Pull request ${{ steps.auto-merge.outputs.pullRequestNumber }} merged!"
      - name: summary
        if: steps.auto-merge.outputs.mergeResult == 'merged'
        run: echo "### Pull request ${{ steps.auto-merge.outputs.pullRequestNumber }} merged!" >> "$GITHUB_STEP_SUMMARY"
