name: Sync Labels
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-22.04'"
        required: false
        type: string
        default: "ubuntu-22.04"
jobs:
  sync:
    name: Sync Labels
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync Labels
        uses: b4b4r07/github-labeler@master
        id: labeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}