name: Package Unit
on:
  workflow_call:
    inputs:
      workspaces:
        description: "are workspaces enabled"
        required: false
        type: string
        default: "false"
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      nodeOptions:
        description: "Node options"
        required: false
        type: string
        default: ""
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18, 19]
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ matrix.node }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      # build
      - name: Workspace Build
        id: workspace-build
        if: inputs.workspaces == 'true'
        run: yarn workspaces foreach run build
        shell: bash
      - name: Build
        id: build
        if: inputs.workspaces != 'true'
        run: yarn build
        shell: bash
      # CumulusDS/yarn-test-action
      - name: Check Licenses
        id: check-licenses
        run: yarn build:license-checker
        shell: bash
      # test
      - name: Yarn workspaces test
        id: yarn-workspaces-test
        if: inputs.workspaces == 'true'
        run:  yarn workspaces foreach run test
        shell: bash
      - name: Yarn test
        id: yarn-test
        if: inputs.workspaces != 'true'
        uses: CumulusDS/yarn-test-action@v1
        with:
          args: ${{ inputs.nodeOptions }}
      - name: Upload artifact
        if: always()
        uses: CumulusDS/unit-end-action@v1
