name: Package Publish
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: "Version of Node to use"
        required: false
        type: string
        default: "14"
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      npmjsPublishToken:
        description: "NPMJS token with publishing permissions"
        required: false
        type: string
        default: "NPM_TOKEN_PUBLISH"
      workspaces:
        description: "are workspaces enabled"
        required: false
        type: string
        default: "false"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: set node publish token
        uses: CumulusDS/workflows/.github/actions/set-publish-token@master
        with:
          npmjsPublishToken: ${{ secrets[inputs.npmjsPublishToken] }}
      - name: Publish
        if: inputs.workspaces != 'true'
        run: yarn npm publish
      - name: Publish (workspaces)
        if: inputs.workspaces == 'true'
        run: yarn publish
      - name: Summary (success)
        if: success()
        run: echo "### Published version $(jq .version package.json) to NPM" >> $GITHUB_STEP_SUMMARY
      - name: Summary (failure)
        if: failure()
        run: echo "### Failed to publish version $(jq .version package.json) to NPM!" >> $GITHUB_STEP_SUMMARY
