name: Prerelease delete
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: "Version of Node to use"
        required: false
        type: string
        default: "14"
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      githubEventName:
        required: false
        type: string
        default: "${{ github.event_name }}"
      githubEventAction:
        description: 'Github event action'
        required: false
        type: string
        default: "${{ github.event.action }}"
      npmjsPublishToken:
        description: "NPMJS token with publishing permissions"
        required: false
        type: string
        default: "NPM_TOKEN_PUBLISH"
jobs:
  remove-tag:
    name: Remove distribution tag
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: Set feature stage
        id: feature
        uses: CumulusDS/feature-stage-action@v2
        with:
          githubEventName: ${{ inputs.githubEventName }}
          githubEventRef: ${{ inputs.githubEventRef }}
      - name: set node publish token
        uses: CumulusDS/workflows/.github/actions/set-publish-token@master
        with:
          npmjsPublishToken: ${{ secrets[inputs.npmjsPublishToken] }}
      - name: Untag
        run: yarn run npm:tag:remove ${{ steps.feature.outputs.stage }}