name: Package Unit
on:
  workflow_call:
    inputs:
      workspaces:
        description: "are workspaces enabled"
        required: false
        type: string
        default: "false"
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      nodeOptions:
        description: "Node options"
        required: false
        type: string
        default: ""
      nodeVersions:
        description: "Array list of node versions to run tests against.  Default '[14, 16, 18, 19]'"
        required: false
        type: string
        default: "[14, 16, 18, 19]"
      timeoutMinutes:
        description: "job timeout time, in minutes"
        required: false
        type: string
        default: "10"
      failFast:
        description: "fail fast option for matrix"
        required: false
        type: string
        default: "true"
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: ${{ fromJSON(inputs.failFast) }}
      matrix:
        node: ${{ fromJSON(inputs.nodeVersions) }}
    timeout-minutes: ${{ fromJSON(inputs.timeoutMinutes) }}
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ matrix.node }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: Yarn test
        id: yarn-test
        uses: CumulusDS/yarn-test-action@v1
        with:
          args: ${{ inputs.nodeOptions }}
          workspaces: ${{ inputs.workspaces }}
      - name: Upload artifact
        if: always()
        uses: CumulusDS/unit-end-action@v1
