name: Package Checker
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-22.04'"
        required: false
        type: string
        default: "ubuntu-22.04"
jobs:
  yarn:
    name: Yarn Lock Changes
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 5
    steps:
      - name: Yarn Lock Changes
        uses: CumulusDS/yarn-lock-changes-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  deprecation:
    name: Package Deprecations
    timeout-minutes: 5
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Check for deprecated packages
        uses: CumulusDS/deprecated-packages-action@v1