name: Package Publish
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-latest'"
        required: false
        type: string
        default: "ubuntu-latest"
      access:
        description: "The access for the published package (public or restricted)"
        required: false
        type: string
        default: "restricted"
      nodeVersion:
        description: "Version of Node to use"
        required: false
        type: string
        default: "20"
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      npmjsPublishToken:
        description: "NPMJS token with publishing permissions"
        required: false
        type: string
        default: "NPM_TOKEN_PUBLISH"
      workspaces:
        description: "are workspaces enabled?  should this run for all workspaces?"
        required: false
        type: string
        default: "false"
      workspace:
        description: "specific workspace to run against"
        required: false
        type: string
        default: ""
jobs:
  publish:
    name: Publish
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: CumulusDS/workflows-public/.github/actions/workflow-setup-action@master
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: set node publish token
        uses: CumulusDS/workflows-public/.github/actions/set-publish-token@master
        with:
          npmjsPublishToken: ${{ secrets[inputs.npmjsPublishToken] }}
      # publish
      - name: Publish (packages/hybrid)
        if: inputs.workspaces != 'true' && inputs.workspace == ''
        run: yarn npm publish --access ${{ inputs.access }}
      - name: Publish (all workspaces)
        if: inputs.workspaces == 'true' && inputs.workspace == ''
        run: yarn workspaces foreach --no-private npm publish --access ${{ inputs.access }}
      - name: Publish ${{ inputs.workspace }}
        if: inputs.workspaces != 'true' && inputs.workspace != ''
        run: yarn workspace ${{ inputs.workspace }} run npm publish --access ${{ inputs.access }}
      # $GITHUB_STEP_SUMMARY - success
      - name: Summary (packages/hybrid)
        if: success() && inputs.workspaces != 'true' && inputs.workspace == ''
        run: echo "### Published $(jq '.name' package.json) version $(jq .version package.json) to NPM" >> "$GITHUB_STEP_SUMMARY"
      - name: Summary (all workspaces)
        if: success() && inputs.workspaces == 'true' && inputs.workspace == ''
        run: |
          pjs=($(find . -type f -name package.json -not -path "./node_modules/*"))
          for version in "${pjs[@]}"; do
            if [[ "$(jq -r '.private' ${version})" != "true" ]]; then
              echo "### Published $(jq '.name' ${version}) version $(jq '.version' ${version}) to NPM" >> "$GITHUB_STEP_SUMMARY"
            fi
          done
      - name: Summary ${{ inputs.workspace }}
        if: success() && inputs.workspaces != 'true' && inputs.workspace != ''
        run: |
          pjs=($(find . -type f -name package.json -not -path "./node_modules/*"))
          echo "package.json files found: ${pjs[@]}"
          
          for version in "${pjs[@]}"; do
            if [[ "$(jq -r '.name' ${version})" == "${{ inputs.workspace }}" ]]; then 
              echo "### Published $(jq '.name' ${version}) version $(jq '.version' ${version}) to NPM" >> "$GITHUB_STEP_SUMMARY"
            fi
          done
      # $GITHUB_STEP_SUMMARY - failure
      - name: Summary (packages/hybrid)
        if: failure() && inputs.workspaces != 'true' && inputs.workspace == ''
        run: echo "### Failed to publish $(jq '.name' package.json) version $(jq .version package.json) to NPM" >> "$GITHUB_STEP_SUMMARY"
      - name: Summary (all workspaces)
        if: failure() && inputs.workspaces == 'true' && inputs.workspace != ''
        run: |
          pjs=($(find . -type f -name package.json -not -path "./node_modules/*"))
          for version in "${pjs[@]}"; do
            if [[ "$(jq -r '.private' ${version})" != "true" ]]; then
              echo "### Failed to publish $(jq '.name' ${version}) version $(jq '.version' ${version}) to NPM" >> "$GITHUB_STEP_SUMMARY"
            fi
          done
      - name: Summary ${{ inputs.workspace }}
        if: failure() && inputs.workspaces != 'true' && inputs.workspace != ''
        run: |
          pjs=($(find . -type f -name package.json -not -path "./node_modules/*"))
          echo "package.json files found: ${pjs[@]}"
          
          for version in "${pjs[@]}"; do
            if [[ "$(jq -r '.name' ${version})" == "${{ inputs.workspace }}" ]]; then 
              echo "### Failed to publish $(jq '.name' ${version}) version $(jq '.version' ${version}) to NPM" >> "$GITHUB_STEP_SUMMARY"
            fi
          done
