name: Package Unit
on:
  workflow_call:
    inputs:
      workspaces:
        description: "are workspaces enabled?  should this run for all workspaces?"
        required: false
        type: string
        default: "false"
      workspace:
        description: "specific workspoace to run against"
        required: false
        type: string
        default: ""
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      nodeOptions:
        description: "Node options"
        required: false
        type: string
        default: ""
      nodeVersions:
        description: "Array list of node versions to run tests against.  Default '[18, 20, 21]'"
        required: false
        type: string
        default: "[18, 20, 21]"
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-latest'"
        required: false
        type: string
        default: "ubuntu-latest"
      timeoutMinutes:
        description: "Timeout in minutes"
        required: false
        type: string
        default: "10"
      failFast:
        description: "fail fast option for matrix"
        required: false
        type: string
        default: "true"
jobs:
  unit:
    name: Unit
    runs-on: ${{ inputs.runsOn }}
    strategy:
      fail-fast: ${{ fromJSON(inputs.failFast) }}
      matrix:
        node: ${{ fromJSON(inputs.nodeVersions) }}
    timeout-minutes: ${{ fromJSON(inputs.timeoutMinutes) }}
    steps:
      - name: Setup
        uses: CumulusDS/workflows-public/.github/actions/workflow-setup-action@master
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      # build packages
      - name: Build
        id: build
        if: inputs.workspaces != 'true' && inputs.workspace == '' # yarn test action will handle specific or multiple workspaces
        run: yarn build
        shell: bash
      - name: Build workspace ${{ inputs.workspace }}
        id: workspace-build
        if: inputs.workspaces != 'true' && inputs.workspace != ''
        run: |
          echo "::group::yarn build single workspace"
          yarn workspace ${{ inputs.workspace }} build
          echo "::endgroup::"
        shell: bash
      - name: Build all workspaces
        id: workspaces-build
        if: inputs.workspaces == 'true' && inputs.workspace == ''
        run: |
          echo "::group::yarn build all workspaces"
          yarn workspaces foreach run build
          echo "::endgroup::"
        shell: bash
      # test
      - name: Yarn test
        id: yarn-test
        uses: CumulusDS/workflows-public/.github/actions/yarn-test-action@master
        with:
          workspace: ${{ inputs.workspace }}
          workspaces: ${{ inputs.workspaces }}
        env:
          NODE_OPTIONS: ${{ inputs.nodeOptions }}
      - name: Upload artifact
        if: always()
        uses: CumulusDS/workflows-public/.github/actions/unit-end-action@master
