name: Serverless Deploy
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: "serverless.yml"
      githubEventName:
        required: false
        type: string
        default: "${{ github.event_name }}"
      githubEventAction:
        description: 'Github event action'
        required: false
        type: string
        default: "${{ github.event.action }}"
      loneRegion:
        description: "Should deployment only happen in one region?  If yes, provide that region"
        required: false
        type: string
        default: ""
      nodeVersion:
        description: "Node version to use"
        required: false
        type: string
        default: "16"
      ref:
        description: ""
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch-depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  `yarn` or `yarn3`"
        required: false
        type: string
        default: "yarn3"
      role:
        description: "Role to assume for integration testing"
        required: false
        type: string
        default: "ContinuousIntegration"
      hyphen:
        description: "Is the role-name hyphenated?"
        required: false
        type: string
        default: "false"
      durationSeconds:
        description: "Duration in seconds to assume role for"
        required: false
        type: string
        default: "1200"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NODE_AUTH_TOKEN"
      awsAccessKeyId:
        description: "Key ID"
        required: false
        type: string
        default: "AWS_ACCESS_KEY_ID"
      awsSecretAccessKey:
        description: "Key secret"
        required: false
        type: string
        default: "AWS_SECRET_ACCESS_KEY"
      stackPolicyFile:
        description: "Stack policy file"
        required: false
        type: string
        default: "templates/policies/serverless.json"
jobs:
  matrix:
    name: Build Matrix
    runs-on: ubuntu-22.04
    outputs:
      stage: ${{ steps.feature.outputs.stage }}
      service: ${{ steps.serverless.outputs.stage }}
      matrixRegion: ${{ steps.set-matrix.outputs.matrixRegions }}
      matrixStage:  ${{ steps.set-matrix.outputs.matrixStages }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetchDepth }}
      - name: Get serverless properties
        id: serverless
        uses: CumulusDS/get-yaml-paths-action@v1
        with:
          file: ${{ inputs.config }}
          service: service
      - name: Set feature stage
        id: feature
        uses: CumulusDS/feature-stage-action@v2
        with:
          githubEventName: ${{ inputs.githubEventName }}
      - name: set matrix
        id: set-matrix
        uses: CumulusDS/set-matrix-action@master
        with:
          githubEventAction: ${{ inputs.githubEventAction }}
          loneRegion: ${{ inputs.loneRegion }}
  deploy:
    name: Deploy ${{ matrix.stage }} (${{ matrix.region }})
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    needs: matrix
    strategy:
      matrix:
        stage: ${{fromJson(needs.matrix.outputs.matrixStage)}}
        region: ${{fromJson(needs.matrix.outputs.matrixRegion)}}
      fail-fast: false
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: determine AWS account
        id: account
        uses: CumulusDS/workflows/.github/actions/determine-account@reusable-test
        env:
          FEATURE_STAGE: ${{ matrix.stage }}
          DEV: ${{ secrets.STS_DEV_AWS_ACCOUNT_ID }}
          PROD: ${{ secrets.STS_PROD_AWS_ACCOUNT_ID }}
      - name: Assume Role
        id: role
        uses: CumulusDS/assume-role-action@v1
        with:
          file: ${{ inputs.config }}
          role: ${{ inputs.role }}
          hyphen: ${{ inputs.hyphen }}
          region: "${{ matrix.region }}"
          account_id: ${{ env.AWS_ACCOUNT }}
          duration_seconds: ${{ inputs.durationSeconds }}
          aws_access_key_id: ${{ secrets[inputs.awsAccessKeyId] }}
          aws_secret_access_key: ${{ secrets[inputs.awsSecretAccessKey] }}
      - name: serverless deploy
        uses: CumulusDS/sls-deploy-remove-action@v1
        with:
          service: ${{ steps.role.outputs.service }}
          stack_policy_file: ${{ inputs.stackPolicyFile }}
          args: --config ${{ inputs.config }}
