name: Delete Feature Branch
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: "serverless.yml"
      githubEventName:
        required: false
        type: string
        default: "${{ github.event_name }}"
      githubEventAction:
        description: 'Github event action'
        required: false
        type: string
        default: "${{ github.event.action }}"
      githubEventRef:
        required: false
        type: string
        default: "${{ github.event.ref }}"
      loneRegion:
        description: "Should deployment only happen in one region?  If yes, provide that region"
        required: false
        type: string
        default: ""
      nodeVersion:
        description: "Node version to use"
        required: false
        type: string
        default: "16"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      fetchDepth:
        description: "Checkout fetch-depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  `yarn` or `yarn3`"
        required: false
        type: string
        default: "yarn3"
      role:
        description: "Role to assume for integration testing"
        required: false
        type: string
        default: "ContinuousIntegration"
      hyphen:
        description: "Is the role-name hyphenated?"
        required: false
        type: string
        default: "true"
      accountIdSecret:
        description: "AccountID secret for reference"
        required: false
        type: string
        default: "STS_DEV_AWS_ACCOUNT_ID"
      durationSeconds:
        description: "Duration in seconds to assume role for"
        required: false
        type: string
        default: "1200"
      awsAccessKeyId:
        description: "Key ID"
        required: false
        type: string
        default: "AWS_ACCESS_KEY_ID"
      awsSecretAccessKey:
        description: "Key secret"
        required: false
        type: string
        default: "AWS_SECRET_ACCESS_KEY"
      globalTableName:
        description: "Global table to enable PITR recovery on"
        required: false
        type: string
        default: ""
jobs:
  matrix:
    name: Build Matrix
    runs-on: ubuntu-22.04
    outputs:
      stage: ${{ steps.feature.outputs.stage }}
      service: ${{ steps.serverless.outputs.stage }}
      matrixRegion: ${{ steps.set-matrix.outputs.matrixRegions }}
      matrixStage:  ${{ steps.set-matrix.outputs.matrixStages }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetchDepth }}
      - name: Get serverless properties
        id: serverless
        uses: CumulusDS/get-yaml-paths-action@v1
        with:
          file: ${{ inputs.config }}
          service: service
      - name: Set feature stage
        id: feature
        uses: CumulusDS/feature-stage-action@v2
        with:
          githubEventName: ${{ inputs.githubEventName }}
          githubEventRef: ${{ inputs.githubEventRef }}
      - name: set matrix
        id: set-matrix
        uses: CumulusDS/set-matrix-action@master
        with:
          githubEventAction: ${{ inputs.githubEventAction }}
          loneRegion: ${{ inputs.loneRegion }}
  deprovision:
    name: Deprovision
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs:
      - matrix
    strategy:
      matrix:
        stage: ${{fromJson(needs.matrix.outputs.matrixStage)}}
        region: ${{fromJson(needs.matrix.outputs.matrixRegion)}}
      fail-fast: false
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: Assume CI Role
        id: role
        uses: CumulusDS/assume-role-action@v1
        with:
          file: ${{ inputs.config }}
          role: ${{ inputs.role }}
          hyphen: ${{ inputs.hyphen }}
          region: "${{ matrix.region }}"
          account_id: ${{ secrets[inputs.accountIdSecret] }}
          duration_seconds: ${{ inputs.durationSeconds }}
          aws_access_key_id: ${{ secrets[inputs.awsAccessKeyId] }}
          aws_secret_access_key: ${{ secrets[inputs.awsSecretAccessKey] }}
      - name: Remove global tables (conditional)
        # delete the us-east-2 replica from us-east-1 matrix job first to enable deletion of the us-east-1 stack.
        if: | # us-east-2 stack doesn't care about the table since it isn't a part of the stack in us-east-2
         matrix.region == 'us-east-1' && inputs.globalTableName != ''
        env:
          SERVICE: ${{ steps.role.outputs.service }}
          STAGE: ${{ matrix.stage }}
          TABLE: ${{ inputs.globalTableName }}
        run: |
          aws dynamodb delete-table --region us-east-2 --table-name \
            $SERVICE-$STAGE-$TABLE
          echo "Waiting until table doesn't exist"
          aws dynamodb wait table-not-exists --region us-east-2 --table-name \
            $SERVICE-$STAGE-$TABLE
          sleep 60 # wait for last writes to us-east-1 table
        continue-on-error: true
      - name: serverless remove
        uses: CumulusDS/sls-deploy-remove-action@v1
        with:
          service: ${{ steps.role.outputs.service }}
          stage: ${{ matrix.stage }}
          action: remove
          verbose: true
          debug: false
          args: --config ${{ inputs.config }}
