name: Serverless Unit
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: "Version of Node to use"
        required: false
        type: string
        default: "16"
      ref:
        description: "Ref to checkout.  Should be blank in most cases to let the system determine"
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  yarn3 vs yarn"
        required: false
        type: string
        default: "yarn3"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      nodeOptions:
        description: "Node options"
        required: false
        type: string
        default: ""
      workspace:
        description: "specific workspace to run serverless unit against, should be blank or only one for serverless project"
        required: false
        type: string
        default: ""
      runsOn:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-22.04"
      timeoutMinutes:
        description: "Timeout in minutes"
        required: false
        type: string
        default: "20"
jobs:
  unit:
    name: Unit
    runs-on: ${{ fromJSON(inputs.runsOnLabel) }}
    timeout-minutes: ${{ fromJSON(inputs.timeoutMinutes) }}
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: Build (if package.json key exists)
        run: |
          if [[ $(cat package.json | jq '.scripts.build') == null ]]; then 
            echo "yarn build is not required"
          else
            yarn build
          fi
      - name: Yarn Test
        uses: CumulusDS/yarn-test-action@master
        with:
          args: ${{ inputs.nodeOptions }}
          workspace: ${{ inputs.workspace }}
      - name: Upload
        uses: CumulusDS/unit-end-action@v2