name: Serverless Deploy
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: "serverless.yml"
      githubEventName:
        required: false
        type: string
        default: "${{ github.event_name }}"
      githubEventAction:
        description: 'Github event action'
        required: false
        type: string
        default: "${{ github.event.action }}"
      loneRegion:
        description: "Should deployment only happen in one region?  If yes, provide that region"
        required: false
        type: string
        default: ""
      nodeVersion:
        description: "Node version to use"
        required: false
        type: string
        default: "16"
      ref:
        description: ""
        required: false
        type: string
        default: ""
      fetchDepth:
        description: "Checkout fetch-depth"
        required: false
        type: string
        default: "0"
      packageManager:
        description: "Package manager to use.  `yarn` or `yarn3`"
        required: false
        type: string
        default: "yarn3"
      role:
        description: "Role to assume for integration testing"
        required: false
        type: string
        default: "ContinuousIntegration"
      hyphen:
        description: "Is the role-name hyphenated?"
        required: false
        type: string
        default: "true"
      durationSeconds:
        description: "Duration in seconds to assume role for"
        required: false
        type: string
        default: "1200"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NPM_TOKEN_READ_ONLY"
      awsAccessKeyId:
        description: "Key ID"
        required: false
        type: string
        default: "AWS_ACCESS_KEY_ID"
      awsSecretAccessKey:
        description: "Key secret"
        required: false
        type: string
        default: "AWS_SECRET_ACCESS_KEY"
      stackPolicyFile:
        description: "Stack policy file"
        required: false
        type: string
        default: "templates/policies/serverless.json"
      runsOnLabel:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest-4-cores"
      globalTableName:
        description: "Global table to enable PITR recovery on"
        required: false
        type: string
        default: ""
    outputs:
      matrixStages:
        description: "Stage used in output matrix"
        value: ${{ jobs.matrix.outputs.matrixStage }}
      matrixRegions:
        description: "List of matrix regions set in output matrix"
        value: ${{ jobs.matrix.outputs.matrixRegion }}
      service:
        description: "The service this called workflow is running for"
        value: ${{ jobs.matrix.outputs.service }}
jobs:
  matrix:
    name: Build Matrix
    runs-on: ubuntu-22.04
    outputs:
      stage: ${{ steps.feature.outputs.stage }}
      service: ${{ steps.serverless.outputs.stage }}
      matrixRegion: ${{ steps.set-matrix.outputs.matrixRegions }}
      matrixStage:  ${{ steps.set-matrix.outputs.matrixStages }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetchDepth }}
      - name: Get serverless properties
        id: serverless
        uses: CumulusDS/get-yaml-paths-action@v1
        with:
          file: ${{ inputs.config }}
          service: service
      - name: Set feature stage
        id: feature
        uses: CumulusDS/feature-stage-action@v2
        with:
          githubEventName: ${{ inputs.githubEventName }}
      - name: set matrix
        id: set-matrix
        uses: CumulusDS/set-matrix-action@master
        with:
          githubEventAction: ${{ inputs.githubEventAction }}
          loneRegion: ${{ inputs.loneRegion }}
  deploy:
    name: Deploy ${{ matrix.stage }} (${{ matrix.region }})
    runs-on: ${{ inputs.runsOnLabel }}
    timeout-minutes: 20
    needs: matrix
    strategy:
      matrix:
        stage: ${{fromJson(needs.matrix.outputs.matrixStage)}}
        region: ${{fromJson(needs.matrix.outputs.matrixRegion)}}
      fail-fast: false
    steps:
      - name: Setup
        uses: CumulusDS/workflow-setup-action@v2
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          npmToken: ${{ secrets[inputs.npmjsToken] }}
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ inputs.fetchDepth }}
          packageManager: ${{ inputs.packageManager }}
      - name: determine AWS account
        id: account
        uses: CumulusDS/workflows/.github/actions/determine-account@master
        env:
          FEATURE_STAGE: ${{ matrix.stage }}
          DEV: ${{ secrets.STS_DEV_AWS_ACCOUNT_ID }}
          PROD: ${{ secrets.STS_PROD_AWS_ACCOUNT_ID }}
      - name: Assume Role
        id: role
        uses: CumulusDS/assume-role-action@v1
        with:
          file: ${{ inputs.config }}
          role: ${{ inputs.role }}
          hyphen: ${{ inputs.hyphen }}
          region: "${{ matrix.region }}"
          account_id: ${{ env.AWS_ACCOUNT }}
          duration_seconds: ${{ inputs.durationSeconds }}
          aws_access_key_id: ${{ secrets[inputs.awsAccessKeyId] }}
          aws_secret_access_key: ${{ secrets[inputs.awsSecretAccessKey] }}
      - name: Debug
        run: |
          echo "matrix.region: ${{ matrix.region }}"
          echo "inputs.globalTableName: ${{ inputs.globalTableName }}"
      - name: Build (if package.json key exists)
        run: |
          if [[ $(cat package.json | jq '.scripts.build') == null ]]; then 
            echo "yarn build is not required"
          else
            yarn build
          fi
      - name: set git user
        run: git config --local user.name ${GITHUB_ACTOR}
      - name: Global Table Wait (conditional)
        if: | # Only needed from us-east-1 region as primary table is created here
          matrix.region == 'us-east-1' && inputs.globalTableName != ''
        run: | # https://github.com/tveal/serverless-dynamodb-global-table-v2-plugin#advanced
          export GTV2_RETRY=30
          export GTV2_RETRY_PAUSE_MILLIS=20000
      - name: serverless deploy
        uses: CumulusDS/sls-deploy-remove-action@v1
        with:
          service: ${{ steps.role.outputs.service }}
          stack_policy_file: ${{ inputs.stackPolicyFile }}
          verbose: true
          args: --config ${{ inputs.config }}
      - name: Enable Global Table PITR (conditional)
        if: | # enable from us-east-1 region only after replicas are created
          matrix.region == 'us-east-1' && inputs.globalTableName != ''
        env:
          SERVICE: ${{ steps.role.outputs.service }}
          STAGE: ${{ matrix.stage }}
          TABLE: ${{ inputs.globalTableName }}
        run: |
          aws dynamodb wait table-exists --region us-east-2 --table-name \
            $SERVICE-$STAGE-$TABLE
          aws dynamodb update-continuous-backups --region us-east-2 --table-name \
            $SERVICE-$STAGE-$TABLE \
            --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true
          if [[ "$STAGE" == "prod" ]]; then
            aws dynamodb wait table-exists --region ap-southeast-1 --table-name \
              $SERVICE-$STAGE}-$TABLE
            aws dynamodb update-continuous-backups --region ap-southeast-1 --table-name \
              $SERVICE-$STAGE-$TABLE \
              --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true
            aws dynamodb wait table-exists --region eu-west-1 --table-name \
              $SERVICE-$STAGE-$TABLE
            aws dynamodb update-continuous-backups --region eu-west-1 --table-name \
              $SERVICE-$STAGE-$TABLE \
              --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true
          fi