name: Stale Stack Cleanup
on:
  workflow_call:
    inputs:
      file:
        description: "File to get yaml properties from if not defined with the service input Required: false Default: 'serverless.yml'"
        required: false
        type: string
        default: "serverless.yml"
      role:
        description: "Role to assume for integration testing"
        required: false
        type: string
        default: "ContinuousIntegration"
      hyphen:
        description: "Is the role-name hyphenated?"
        required: false
        type: string
        default: "false"
      durationSeconds:
        description: "Duration in seconds to assume role for"
        required: false
        type: string
        default: "1200"
      npmjsToken:
        description: "NPMJS auth token"
        required: false
        type: string
        default: "NODE_AUTH_TOKEN"
      accountId:
        description: "Account ID.  Should only be dev"
        required: false
        type: string
        default: "STS_DEV_AWS_ACCOUNT_ID"
      awsAccessKeyId:
        description: "Key ID"
        required: false
        type: string
        default: "AWS_ACCESS_KEY_ID"
      awsSecretAccessKey:
        description: "Key secret"
        required: false
        type: string
        default: "AWS_SECRET_ACCESS_KEY"
jobs:
  cleanup:
    name: Stack Cleanup
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        region:
          - us-east-1
          - us-east-2
    steps:
      - name: Cleanup Stacks
        id: cleanup
        uses: CumulusDS/stack-cleanup-action@v1
        with:
          file: ${{ inputs.file }}
          region: ${{ matrix.region }}
          role: ${{ inputs.role }}
          hyphen: ${{ inputs.hyphen }}
          account_id: ${{ secrets[inputs.accountId] }}
          duration_seconds: ${{ inputs.durationSeconds }}
          aws_access_key_id: ${{ secrets[inputs.awsAccessKeyId] }}
          aws_secret_access_key: ${{ secrets[inputs.awsSecretAccessKey] }}